phoenix:
    build: .
    volumes:
        - .:/app
        - .mix:/root/.mix
    command: /bin/sh -c "npm install && mix local.hex --force && mix deps.get && mix hex.info && mix phoenix.server"
    ports:
      - 4000:4000
            
